# Generated by Django 5.1.4 on 2026-06-17 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='expenses.groupe')),
                ('payeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses_payees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_part', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='expenses.depense')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
                'unique_together': {('depense', 'participant')},
            },
        ),
        migrations.AddField(
            model_name='depense',
            name='participants',
            field=models.ManyToManyField(related_name='depenses_participees', through='expenses.Part', to=settings.AUTH_USER_MODEL),
        ),
    ]
