# Generated by Django 5.1.4 on 2026-06-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_depense_part_depense_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depense',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Dépense', 'verbose_name_plural': 'Dépenses'},
        ),
        migrations.RenameField(
            model_name='depense',
            old_name='date',
            new_name='date_creation',
        ),
    ]
